version: '3.1'

volumes:
  you_and_tube_postgres:

services:
  you_and_tube_postgres:
    env_file: .env
    image: postgres
    restart: always
    container_name: you_and_tube_postgres
    environment:
      POSTGRES_DB: "you_and_tube"
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - you_and_tube_postgres:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432

# redis:
#   container_name: you_and_tube_redis
#   image: redis:latest
#   ports:
#     - "6379:6379"
