export const VideoNoPreview = () => {
  return (
    <>
      <svg
        xmlns="http://www.w3.org/2000/svg"
        version="1.1"
        xmlnsXlink="http://www.w3.org/1999/xlink"
        xmlnssvgjs="http://svgjs.com/svgjs"
        width="100%"
        height="100%"
        preserveAspectRatio="none"
        viewBox="0 0 1080 720"
      >
        <g mask='url("#SvgjsMask1351")' fill="none">
          <rect
            width="1080"
            height="720"
            x="0"
            y="0"
            fill="url(#SvgjsLinearGradient1352)"
          ></rect>
          <use xlinkHref="#SvgjsSymbol1359" x="0" y="0"></use>
          <use xlinkHref="#SvgjsSymbol1359" x="720" y="0"></use>
        </g>
        <defs>
          <mask id="SvgjsMask1351">
            <rect width="1080" height="720" fill="#ffffff"></rect>
          </mask>
          <linearGradient
            x1="8.33%"
            y1="-12.5%"
            x2="91.67%"
            y2="112.5%"
            gradientUnits="userSpaceOnUse"
            id="SvgjsLinearGradient1352"
          >
            <stop stopColor="#0e2a47" offset="0"></stop>
            <stop stopColor="rgba(0, 49, 112, 1)" offset="1"></stop>
          </linearGradient>
          <path
            d="M-1 0 a1 1 0 1 0 2 0 a1 1 0 1 0 -2 0z"
            id="SvgjsPath1355"
          ></path>
          <path
            d="M-3 0 a3 3 0 1 0 6 0 a3 3 0 1 0 -6 0z"
            id="SvgjsPath1354"
          ></path>
          <path
            d="M-5 0 a5 5 0 1 0 10 0 a5 5 0 1 0 -10 0z"
            id="SvgjsPath1353"
          ></path>
          <path d="M2 -2 L-2 2z" id="SvgjsPath1357"></path>
          <path d="M6 -6 L-6 6z" id="SvgjsPath1356"></path>
          <path d="M30 -30 L-30 30z" id="SvgjsPath1358"></path>
        </defs>
        <symbol id="SvgjsSymbol1359">
          <use xlinkHref="#SvgjsPath1353" x="30" y="30" stroke="#1c538e"></use>
          <use xlinkHref="#SvgjsPath1354" x="30" y="90" stroke="#1c538e"></use>
          <use
            xlinkHref="#SvgjsPath1355"
            x="30"
            y="150"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1356"
            x="30"
            y="210"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="30"
            y="270"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="30"
            y="330"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1357"
            x="30"
            y="390"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1356"
            x="30"
            y="450"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="30"
            y="510"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1356"
            x="30"
            y="570"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1356"
            x="30"
            y="630"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="30"
            y="690"
            stroke="#1c538e"
          ></use>
          <use xlinkHref="#SvgjsPath1353" x="90" y="30" stroke="#1c538e"></use>
          <use xlinkHref="#SvgjsPath1355" x="90" y="90" stroke="#1c538e"></use>
          <use
            xlinkHref="#SvgjsPath1356"
            x="90"
            y="150"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="90"
            y="210"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1356"
            x="90"
            y="270"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1354"
            x="90"
            y="330"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1355"
            x="90"
            y="390"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1357"
            x="90"
            y="450"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="90"
            y="510"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1356"
            x="90"
            y="570"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1356"
            x="90"
            y="630"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1358"
            x="90"
            y="690"
            stroke="#1c538e"
            strokeWidth="3"
          ></use>
          <use
            xlinkHref="#SvgjsPath1357"
            x="150"
            y="30"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1355"
            x="150"
            y="90"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1358"
            x="150"
            y="150"
            stroke="#1c538e"
            strokeWidth="3"
          ></use>
          <use
            xlinkHref="#SvgjsPath1356"
            x="150"
            y="210"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1358"
            x="150"
            y="270"
            stroke="#1c538e"
            strokeWidth="3"
          ></use>
          <use
            xlinkHref="#SvgjsPath1357"
            x="150"
            y="330"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1356"
            x="150"
            y="390"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1358"
            x="150"
            y="450"
            stroke="#1c538e"
            strokeWidth="3"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="150"
            y="510"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="150"
            y="570"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="150"
            y="630"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="150"
            y="690"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1355"
            x="210"
            y="30"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1356"
            x="210"
            y="90"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1358"
            x="210"
            y="150"
            stroke="#1c538e"
            strokeWidth="3"
          ></use>
          <use
            xlinkHref="#SvgjsPath1354"
            x="210"
            y="210"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1355"
            x="210"
            y="270"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="210"
            y="330"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="210"
            y="390"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1356"
            x="210"
            y="450"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1356"
            x="210"
            y="510"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="210"
            y="570"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="210"
            y="630"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1358"
            x="210"
            y="690"
            stroke="#1c538e"
            strokeWidth="3"
          ></use>
          <use
            xlinkHref="#SvgjsPath1355"
            x="270"
            y="30"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1357"
            x="270"
            y="90"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="270"
            y="150"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="270"
            y="210"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1357"
            x="270"
            y="270"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="270"
            y="330"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1356"
            x="270"
            y="390"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="270"
            y="450"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="270"
            y="510"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1354"
            x="270"
            y="570"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1356"
            x="270"
            y="630"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="270"
            y="690"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1355"
            x="330"
            y="30"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1356"
            x="330"
            y="90"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1357"
            x="330"
            y="150"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1358"
            x="330"
            y="210"
            stroke="#1c538e"
            strokeWidth="3"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="330"
            y="270"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1358"
            x="330"
            y="330"
            stroke="#1c538e"
            strokeWidth="3"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="330"
            y="390"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1355"
            x="330"
            y="450"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1356"
            x="330"
            y="510"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1356"
            x="330"
            y="570"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1358"
            x="330"
            y="630"
            stroke="#1c538e"
            strokeWidth="3"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="330"
            y="690"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="390"
            y="30"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="390"
            y="90"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1354"
            x="390"
            y="150"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1358"
            x="390"
            y="210"
            stroke="#1c538e"
            strokeWidth="3"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="390"
            y="270"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1358"
            x="390"
            y="330"
            stroke="#1c538e"
            strokeWidth="3"
          ></use>
          <use
            xlinkHref="#SvgjsPath1356"
            x="390"
            y="390"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1356"
            x="390"
            y="450"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="390"
            y="510"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1356"
            x="390"
            y="570"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1357"
            x="390"
            y="630"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="390"
            y="690"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1357"
            x="450"
            y="30"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1357"
            x="450"
            y="90"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="450"
            y="150"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1356"
            x="450"
            y="210"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1357"
            x="450"
            y="270"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1356"
            x="450"
            y="330"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1354"
            x="450"
            y="390"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="450"
            y="450"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1357"
            x="450"
            y="510"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="450"
            y="570"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1354"
            x="450"
            y="630"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1356"
            x="450"
            y="690"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="510"
            y="30"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1358"
            x="510"
            y="90"
            stroke="#1c538e"
            strokeWidth="3"
          ></use>
          <use
            xlinkHref="#SvgjsPath1357"
            x="510"
            y="150"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1356"
            x="510"
            y="210"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1356"
            x="510"
            y="270"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1354"
            x="510"
            y="330"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="510"
            y="390"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1357"
            x="510"
            y="450"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="510"
            y="510"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1357"
            x="510"
            y="570"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1354"
            x="510"
            y="630"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="510"
            y="690"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1354"
            x="570"
            y="30"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1358"
            x="570"
            y="90"
            stroke="#1c538e"
            strokeWidth="3"
          ></use>
          <use
            xlinkHref="#SvgjsPath1354"
            x="570"
            y="150"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1354"
            x="570"
            y="210"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1357"
            x="570"
            y="270"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="570"
            y="330"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1357"
            x="570"
            y="390"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="570"
            y="450"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1357"
            x="570"
            y="510"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1357"
            x="570"
            y="570"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="570"
            y="630"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1356"
            x="570"
            y="690"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1354"
            x="630"
            y="30"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1354"
            x="630"
            y="90"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1357"
            x="630"
            y="150"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="630"
            y="210"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1356"
            x="630"
            y="270"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1356"
            x="630"
            y="330"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="630"
            y="390"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1354"
            x="630"
            y="450"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="630"
            y="510"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1356"
            x="630"
            y="570"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="630"
            y="630"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1357"
            x="630"
            y="690"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1357"
            x="690"
            y="30"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1356"
            x="690"
            y="90"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1358"
            x="690"
            y="150"
            stroke="#1c538e"
            strokeWidth="3"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="690"
            y="210"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="690"
            y="270"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="690"
            y="330"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="690"
            y="390"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1355"
            x="690"
            y="450"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="690"
            y="510"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1355"
            x="690"
            y="570"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1353"
            x="690"
            y="630"
            stroke="#1c538e"
          ></use>
          <use
            xlinkHref="#SvgjsPath1354"
            x="690"
            y="690"
            stroke="#1c538e"
          ></use>
        </symbol>
      </svg>
    </>
  );
};
